# Generated by Django 4.2.13 on 2024-07-02 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
