# Generated by Django 4.2.13 on 2024-07-02 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0007_alter_subscription_options_subscription_featured_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["subscription__order", "order", "featured", "-updated"]
            },
        ),
    ]
