# Generated by Django 4.2.13 on 2024-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0008_alter_subscriptionprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Features for pricing, seperated by new line",
                null=True,
            ),
        ),
    ]
